replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

app_image:
  pullPolicy: Always

ingress:
  path: /
  certManagerAnnotationPrefix: cert-manager.io

application:
  pvc:
    enabled: false
    storageClass: "standard"
    accessMode: "ReadWriteOnce"
    size: "1Gi"

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
